services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy_common.conf:/etc/nginx/proxy_common.conf
      - ./jwt_check.conf:/etc/nginx/jwt_check.conf
      - .:/usr/src/app
    depends_on:
      - app
    networks:
      - my_network

  app:
    container_name: nodejs-app
    build:
      context: .
      dockerfile: nodejs.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - redis 
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/mydb
    command: nodemon -L src/index.js
    networks:
      - my_network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network

volumes:
  mongodb_data:
networks:
  my_network:
    driver: bridge
